### ISSUE TITLE
The README.md doesn't show on the home page

### ISSUE THREAD

**Issue by PhilipOakley** [git-for-windows/git-sdk-64#10]
The repo [home page](https://github.com/git-for-windows/git-sdk-64)  says 
"Help people interested in this repository understand your project by adding a README. "

The [PR #8](https://github.com/git-for-windows/git-sdk-64/pull/8) by cooffe to add one was merged on 14 Jun 19 https://github.com/git-for-windows/git-sdk-64/commit/4ea8f3e5cbab52cc290a70e3ae3f2b01d8d14139 but does not show.

I suspect (as I type) that it _should_ have been merged to `master`, not (if I read the page correctly)  `git-for-windows:msys2-runtime-2.x` 

Thoughts?

**Comment by dscho** [comment]
> I suspect (as I type) that it _should_ have been merged to `master`, not (if I read the page correctly) `git-for-windows:msys2-runtime-2.x`

Yes.

**Comment by Atem18** [comment]
@dscho I made a good pull request. Can you review it and accept it please ? Thanks in advance.

**Comment by PhilipOakley** [comment]
The readme simply says that it's "mirroring" the SDK. 

I'd have expected the readme to explain how to use/update the sdk (e.g. the link https://github.com/git-for-windows/git/wiki/Technical-overview, from [our home page](https://gitforwindows.org/)). And, if this is a mirror, the primary location (but I think this is the location...).

Mainly I'm here now because I was getting myself confused about the difference between updating the SDK via the `update-via-pacman.bat`  method, and fetching updates from here (I'm still at 685647a82), and how to handle any divergence... 

In particular `make doc` isn't working for me because asciidoc can't find its config file, which is in /etc/ ...

**Comment by dscho** [comment]
> explain how to use/update the sdk (e.g. the link https://github.com/git-for-windows/git/wiki/Technical-overview, from [our home page](https://gitforwindows.org/)).

It is unfortunately not all that easy.

On a very basic level, it should be totally okay to update via `git pull` (in a Git Bash, with all Git SDK Bash instances closed) all the time.

To make this nicer for GitHub, you should run the first `git pull` with the `--unshallow` option: fetches into shallow clones are really expensive server-side.

Side note: for that reason, I am considering to modify the Git SDK installer to use partial clones instead of shallow clones. (If you feel like taking up that project, I would be delighted.)

Alternatively, and maybe a lot easier on GitHub, would be to require updates to be performed via `update-via-pacman.bat` and not worry about `git status` showing tons of modified/deleted/untracked files.

If we were to make this the recommended (or only) way to update the SDK, we should actually delete `.git/` at the end of the Git SDK installer.

For some time, `pacman -Syu` used to be quite unstable, it would frequently time out. That is the main reason why I left the `.git` directory in there, and why I myself use it to update my own copy of the SDK.

The main problem with `git pull` arises when you install packages that are not tracked in git-sdk-64. Then, a `git pull` would have to be accompanied by a subsequent `pacman -Su` (_without_ `-y`).

I tried to remedy this situation a bit by teaching the `commit-msys2.sh` script in `build-extra` [the `ignore -a` **command](https://github.com/git-for-windows/build-extra/blob/f9dbc27db658c0ddcf2f10bac2122fcef88d5133/commit-msys2.sh#L131-L161): essentially, it will add entries in the `.git/info/exclude` file (which is like `.gitignore`, but untracked) for all the packages you have installed on top of what is tracked. The idea is to run it after every call to `pacman -Su`; That way, `git status` won't show untracked files unless you really have any files that do not belong to any installed package.

> And, if this is a mirror, the primary location (but I think this is the location...).

The Git repository is a mirror in the sense that it is not exactly the authoritative source of truth: the Pacman repositories are. It is a "mirror", but not a "mirror of another Git repository".


> updating the SDK via the `update-via-pacman.bat` method, and fetching updates from here (I'm still at [685647a](https://github.com/git-for-windows/git-sdk-64/commit/685647a82354b6dad0344fc987139b76273f46c0)), and how to handle any divergence...

Whenever I get into such a situation, I run `git fetch && git reset --soft FETCH_HEAD && git stash` or something like that (from a Git Bash, with all instances of Git _SDK_ Bash closed, of course).

> In particular `make doc` isn't working for me because asciidoc can't find its config file, which is in /etc/ ...

Please note that we build Git for Windows' documentation using AsciiDoctor, i.e. [`USE_ASCIIDOCTOR = YesPlease`](https://github.com/git-for-windows/MINGW-packages/blob/faf74a867a5bdaa6cfe4c2c830f566e4c0dfd1d3/mingw-w64-git/PKGBUILD#L103-L105).

Please feel free to provide this information wherever you think is most suitable, whether in a `README.md` in git-sdk-64 or in the Git for Windows wiki.

**Comment by PhilipOakley** [comment]
Yes, it's been on my back-list for far too long.
:disappointed:
