### ISSUE TITLE
Only create desktop icon once, or ideally not at all

### ISSUE THREAD

**Issue by nicholas-ochoa** [git-for-windows/git-sdk-64#36]
I'm not sure if this is a bug, or intended behavior. The desktop icon for git-sdk-64 is recreated every time I open a new shell (if I have previously deleted the icon). This is frustrating behavior and is contrary to how most applications create a desktop icon (optionally, during the installation process).

Commenting out the portion of the `git-sdk.sh` in `profile.d` is easy enough to do, but is it possible to remove this functionality to move it to an installation step instead?

**Comment by dscho** [comment]
This is intended behavior, as the Git for Windows SDK is meant to develop Git for Windows (and without such a desktop icon, it would be less convenient).

**Comment by EndBug** [comment]
I would have no issue with creating it the first time the shell is run, but re-creating every time by default seems a bit excessive to me...

**Comment by dscho** [comment]
I get the sense that y'all are trying to fool me into supporting a usage scenario I really have no inclination to support in addition to all the scenarios I _do_ support.

**Comment by EndBug** [comment]
I'm not trying to fool anyone ahahha
But let me just ask you this: do you keep a desktop shortcut to every single program on your computer ? Because I don't...
Even if someone needs to use this shell every day, they might want to do it through another terminal or just by not opening it through the desktop.

To me, it doesn't seem like allowing users to **NOT** have a somewhat permanent link to your program is _"supporting a [new] usage scenario"_: it would be just be behaving as every other program does and, in my opinion, following common sense.
Recreating the link every time is just forcing users into **your** use case.

I also don't see what usage scenario would this be: if I wanted to keep this link I would just not delete it in the first place...
The fact that this is a tool meant for developers who, presumably, know how to create a desktop shortcut if they want to, makes it even more weird to me.

Anyway, I guess the beauty of Open Source is that you can just edit the script, as @nicholas-ochoa suggested, even though I hope I was able to convey my point of view ✌🏻
