### ISSUE TITLE
Bundle gsudo from https://github.com/gerardog/gsudo for testing permissions issues

### ISSUE THREAD

**Issue by doctorpangloss** [git-for-windows/git-sdk-64#39]
There are a lot of [permissions related issues on Windows](https://www.google.com/search?q=git+permissions+denied+administrator+stackoverflow+site:stackoverflow.com) that may be worth authoring tests for. An easy way to verify the behavior is correct automatically via integration testing is using gsudo for an interactive UAC prompt (or no prompt on a properly configured Windows machine).

Adding gsudo as `usr/bin/sudo.exe` should make it easier to integration test.

**Comment by dscho** [comment]
The most prevalent reason for "Permission denied" errors is a sharing violation (trying to delete files that are still in use).

Since you gave no concrete example (but linked to a Google search, whose results are personalized, read: you see different hits than I do), I cannot give you anything more concrete.

If you want `gsudo` in Git for Windows' SDK, your best bet is to open a PR at https://github.com/msys2/MINGW-packages or https://github.com/msys2/MSYS2-packages (depending whether it is a pure Win32 program or whether it requires the MSYS2/Cygwin runtime), to add it as a Pacman package.

**Comment by rimrul** [comment]
>If you want `gsudo` in Git for Windows' SDK, your best bet is to open a PR at https://github.com/msys2/MINGW-packages or https://github.com/msys2/MSYS2-packages (depending whether it is a pure Win32 program or whether it requires the MSYS2/Cygwin runtime), to add it as a Pacman package.

.NET framework 4.6, so likely no MSYS2 dependency.

**Comment by dscho** [comment]
> .NET framework 4.6, so likely no MSYS2 dependency.

Thank you for digging deeper.
